//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webproject.DAL.DB
{
    using System;
    
    public partial class sp_examinee_exam_history_Result
    {
        public int q_id { get; set; }
        public string emp_id { get; set; }
        public string title { get; set; }
        public string test_type { get; set; }
        public string general_instruction { get; set; }
        public string question { get; set; }
        public string choices { get; set; }
        public string answer { get; set; }
        public string user_answer { get; set; }
        public Nullable<int> exam_id { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<int> attempt { get; set; }
        public Nullable<int> total_score { get; set; }
        public string fullname { get; set; }
        public string passing_rate { get; set; }
        public string essay_flag { get; set; }
        public string user_rights { get; set; }
        public string exam_duration { get; set; }
        public string image_name { get; set; }
        public string choices_img { get; set; }
        public string in_any_order { get; set; }
        public string essay_points { get; set; }
    }
}
