//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webproject.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_questionnaire
    {
        public int q_id { get; set; }
        public Nullable<int> exam_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string title { get; set; }
        public string test_type { get; set; }
        public string general_instruction { get; set; }
        public string question { get; set; }
        public string choices { get; set; }
        public string answer { get; set; }
        public string department { get; set; }
        public string added_by { get; set; }
        public string updated_by { get; set; }
        public string date_added { get; set; }
        public string exam_schedule { get; set; }
        public string allow_access { get; set; }
        public string examinee { get; set; }
        public string time_limit { get; set; }
        public string passing_rate { get; set; }
        public string image_name { get; set; }
        public string choices_img { get; set; }
        public string in_any_order { get; set; }
        public string essay_points { get; set; }
    }
}
