//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webproject.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        public int e_id { get; set; }
        public string emp_id { get; set; }
        public string fullname { get; set; }
        public string department { get; set; }
        public string user_rights { get; set; }
    }
}
