//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webproject.DAL.DB
{
    using System;
    
    public partial class sp_exam_result_by_subj_Result
    {
        public Nullable<int> exam_id { get; set; }
        public string category_name { get; set; }
        public string title { get; set; }
        public Nullable<int> total_percentage { get; set; }
    }
}
