//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webproject.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_unique_codes
    {
        public int uc_id { get; set; }
        public string emp_id { get; set; }
        public string control_no { get; set; }
        public Nullable<int> exam_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string department { get; set; }
        public string isVisitor { get; set; }
        public Nullable<int> category_id { get; set; }
        public string mname { get; set; }
    }
}
