//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webproject.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_examinations
    {
        public int e_id { get; set; }
        public Nullable<int> exam_id { get; set; }
        public Nullable<int> q_id { get; set; }
        public string emp_id { get; set; }
        public string answer { get; set; }
        public Nullable<int> score { get; set; }
        public string date_answered { get; set; }
        public Nullable<int> attempt { get; set; }
        public string exam_duration { get; set; }
        public Nullable<int> total_score { get; set; }
        public string essay_flag { get; set; }
        public string concat_any_order { get; set; }
    }
}
