//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webproject.DAL.DB
{
    using System;
    
    public partial class sp_enumrations_answer_Result
    {
        public Nullable<int> exam_id { get; set; }
        public int q_id { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public string in_any_order { get; set; }
    }
}
